### ISSUE TITLE
是不是不支持多客户端连接？

### ISSUE THREAD

**Issue by ekenchan** [lalawue/m_kcptun#1]

**Comment by lalawue** [comment]
目前不支持

ekenchan <notifications@github.com>于2018年2月8日 周四11:15写道：

**Comment by ekenchan** [comment]
有没有支持的打算呢？感觉epoll的效率要比用libevent2实现的xkcptun要好，但是不支持多客户端有点鸡肋

**Comment by lalawue** [comment]
因为都是自己用的，所以多客户端感觉是没有必要了。

ekenchan <notifications@github.com>于2018年2月8日 周四15:03写道：
